#!/bin/bash
VERSION='2.8.5'
if [ ! -f "./SOURCES/fuse-${VERSION}.tar.gz" ]; then
  wget "http://downloads.sourceforge.net/fuse/fuse-${VERSION}.tar.gz" -O "./SOURCES/fuse-${VERSION}.tar.gz"
fi
rpmbuild --define "_topdir `pwd`" -ba 'SPECS/fuse-vitki.spec'
echo Your packages are available at $PWD/RPMS

