#!/bin/bash
VERSION='2.8.5'
if [ ! -f "./SOURCES/fuse-${VERSION}.tar.gz" ]; then
  wget "http://downloads.sourceforge.net/fuse/fuse-${VERSION}.tar.gz" -O "./SOURCES/fuse-${VERSION}.tar.gz"
  if [ $? -ne 0 ]; then
    echo "Could not download fuse-${VERSION}.tar.gz! Check log!"
    exit 1
  fi
fi
rpmbuild --define "_topdir `pwd`" -ba 'SPECS/fuse-vitki.spec'
if [ $? -eq 0 ]; then
  echo "Your packages are available at $PWD/RPMS."
  exit 0
else
  echo "There are errors. Check log!"
  exit 1
fi
