#!/bin/bash
VERSION='1.78'
if [ ! -f "./SOURCES/s3fs-fuse-${VERSION}.tar.gz" ]; then
  wget "https://github.com/s3fs-fuse/s3fs-fuse/archive/v${VERSION}.tar.gz" -O "./SOURCES/s3fs-fuse-${VERSION}.tar.gz"
fi
rpmbuild --define "_topdir `pwd`" -ba 'SPECS/s3fs-fuse.spec'
echo Your packages are available at $PWD/RPMS

